config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
  	member do
  		put :change
  	end
  end

  devise_for :users
  root 'pages#home'

  get '/about' => 'pages#about'

  
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks, dependent: :destroy       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
	if current_user
		redirect_to tasks_path
		end
	end

  def about
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy, :change]

def index
    @to_do = current_user.tasks.where(state: "to_do")
    @doing = current_user.tasks.where(state: "doing")
    @done = current_user.tasks.where(state: "done")
  end

def show
  end

def new
    @task = Task.new
  end

 def edit
  end

 def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change
    @task.update_attributes(state: params[:state])
    respond_to do |format|
      format.html {redirect_to tasks_path, notice: "Task Update"}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'ToDoS', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
       <li><%= link_to "Tasks", tasks_path  %></li>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='utf-8'>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>We are cool</h1>

app/views/pages/home.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="jumbotron">
			<h1>To Do List</h1>
			<%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-primary btn-block" %>
		</div>
	</div>
</div>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_area :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<tr>
	<td><%= task.content %></td>
	<td><%= link_to 'Show', task %></td>
	<td><%= link_to 'Edit', edit_task_path(task) %></td>
	<td><%= link_to 'X', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% if task.state == "doing" %>
	<td><%= link_to "Mark as To Do", change_task_path(task, state: "to_do"), method: :put %></td>
	<td><%= link_to "Mark as Done", change_task_path(task, state: "done"), method: :put %></td>
	<% else %>
	<td><%= link_to "Mark as Doing", change_task_path(task, state: "doing"), method: :put %></td>
	<% end %>
	</tr>

app/views/tasks/edit.html.erb
<h1 class="text-center">Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-md-4">
    <h1>To Do</h1>
     
    <table class="table">
      <thead>
        <tr>
          <th>Content</th>
        
          <th colspan="2"></th>
        </tr>
      </thead>
     
      <tbody>
        <%= render @to_do %>
      </tbody>
    </table>
     
    <br>
   </div>
   
   <div class="col-md-4">
    <h1>Doing</h1>
   
    <table>
      <thead>
        <tr>
          <th>Content</th>
         
          <th colspan="2"></th>
        </tr>
      </thead>
     
      <tbody>
        <%= render @doing %>
      </tbody>
    </table>
     
   
   </div>

  <div class="col-md-4">
    <h1>Done</h1>
     
    <table>
      <thead>
        <tr>
          <th>Content</th>
          
          <th colspan="2"></th>
        </tr>
      </thead>
     
      <tbody>
        <%= render @done %>
      </tbody>
    </table>
   </div>
  <br>
</div>
<div class="row">
<div class="col-md-3">
  <%= link_to 'New Task', new_task_path, class: "btn btn-primary btn-block" %>
</div>
</div>

app/views/tasks/new.html.erb
<h1 class="text-center">New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
 
<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>
 
<p>
  <strong>State:</strong>
  <%= @task.state %>
</p>
 
<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>